# Generated by Django 6.1.1 on 2026-09-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, verbose_name='Код валюты')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс')),
                ('date', models.DateField(verbose_name='Дата')),
                ('change_percent', models.FloatField(default=0.0, verbose_name='Изменение в %')),
            ],
        ),
    ]
